controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    # Definizione del Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Definizione del Position Controller per i giunti
    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
